image: jangrewe/gitlab-ci-android

variables:
  CMC_API_KEY: s0m3-4p1-k3y

before_script:
  - echo "CMC_API_KEY=$CMC_API_KEY" >> local.properties

stages:
  - lint
  - compile

lint:
  stage: lint
  script:
    - ./gradlew ktlintCheck

compile:
  stage: compile
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/